spring:
  r2dbc:
    url: r2dbc:h2:mem:///stocktest
    username: admin
    password: password
  #  datasource:
  #    url: jdbc:h2:mem:stocktest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    platform: h2
  #    username: admin
  #    password: password
  #    driverClassName: org.h2.Driver
  #    schema: classpath:db/schema.sql
  #    data: classpath:db/data.sql
  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        use_sql_comments: true
  #        format_sql: true
  thymeleaf:
    cache: false
  rsocket:
    server:
      port: 8099
#  rsocket:
#    server:
#      mapping-path: /rsocket
#      transport: websocket
server:
  port: 8118